function h = WSlowpass(fc, M, fs)

% WSlowpass(fc,M [, fs])
%
% Low-Pass Windowed-Sinc Filter (Filter design , cf. DSP guide book chapter 16 page 288 and Table 16-1)
% *****************************
% Low-pass filter to the cutoff frequency fc (where fc < fs / 2). This filter is generated by performing
% The following reasoning:
% - A rectangular window frequency fs cut-off frequency is generated.
% - This window is transformed into time : sinc function ( sinc ) fs argument but of infinite length .
% - Sinc The width is windowed by a Blackman window M + 1 where M is an even integer .
% ( M is selected from the desired roll-off according to the relationship M ~ 4 / BW
% Where BW is the bandwidth roll-off ) .
%
% By default, fs is 44100 Hz .

if (nargin < 3)
   fs = 44100;
end


% Construction of the kernel sinc
% Note: a kernel is the IR of a filter

fc_rel = fc/fs;
h      = zeros(M+1, 1);
pos    = M/2 + 1;

for i = (0:M/2)
   valeur   = sinc(2*fc_rel*i);
   h(pos+i) = valeur;
   h(pos-i) = valeur;
end

% Blackman windowing kernel

h = h .* blackman(M+1);

% Filter Normalisation (unity gain for the DC component) (as H[0] = Sum(1,N) h[n] )

sum = 0;
for i = 1:(M+1)
   sum = sum + h(i);
end
h = h/sum;


return
